//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Cash8.DS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DSSoap", Namespace="http://tempuri.org/")]
    public partial class DS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceIsWorkerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTypesCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDateTimeServerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetStatusSertificatOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDiscountClientsV8DateTime_NEWOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExistsUpdateProrgamOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdateProgramOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNpgsqlNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusSertificatOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadChangeStatusClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadPhoneClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadDeletedItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTovarCheckCDNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataForCasheV8JasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataForCasheV8SuccessfullyOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnlineCasheV8SuccessfullyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataForCasheV8JasonUpdateOnlyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadCDNLogsPortionJasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadDataOnSalesPortionJasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParametersOnBonusProgramOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DS() {
            this.Url = global::Cash8.Properties.Settings.Default.Cash8_DS_DS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ServiceIsWorkerCompletedEventHandler ServiceIsWorkerCompleted;
        
        /// <remarks/>
        public event GetTypesCardCompletedEventHandler GetTypesCardCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetDateTimeServerCompletedEventHandler GetDateTimeServerCompleted;
        
        /// <remarks/>
        public event SetStatusSertificatCompletedEventHandler SetStatusSertificatCompleted;
        
        /// <remarks/>
        public event GetDiscountClientsV8DateTime_NEWCompletedEventHandler GetDiscountClientsV8DateTime_NEWCompleted;
        
        /// <remarks/>
        public event ExistsUpdateProrgamCompletedEventHandler ExistsUpdateProrgamCompleted;
        
        /// <remarks/>
        public event GetUpdateProgramCompletedEventHandler GetUpdateProgramCompleted;
        
        /// <remarks/>
        public event GetNpgsqlNewCompletedEventHandler GetNpgsqlNewCompleted;
        
        /// <remarks/>
        public event GetStatusSertificatCompletedEventHandler GetStatusSertificatCompleted;
        
        /// <remarks/>
        public event UploadChangeStatusClientsCompletedEventHandler UploadChangeStatusClientsCompleted;
        
        /// <remarks/>
        public event UploadPhoneClientsCompletedEventHandler UploadPhoneClientsCompleted;
        
        /// <remarks/>
        public event UploadDeletedItemsCompletedEventHandler UploadDeletedItemsCompleted;
        
        /// <remarks/>
        public event GetTovarCheckCDNCompletedEventHandler GetTovarCheckCDNCompleted;
        
        /// <remarks/>
        public event GetDataForCasheV8JasonCompletedEventHandler GetDataForCasheV8JasonCompleted;
        
        /// <remarks/>
        public event GetDataForCasheV8SuccessfullyCompletedEventHandler GetDataForCasheV8SuccessfullyCompleted;
        
        /// <remarks/>
        public event OnlineCasheV8SuccessfullyCompletedEventHandler OnlineCasheV8SuccessfullyCompleted;
        
        /// <remarks/>
        public event GetDataForCasheV8JasonUpdateOnlyCompletedEventHandler GetDataForCasheV8JasonUpdateOnlyCompleted;
        
        /// <remarks/>
        public event UploadCDNLogsPortionJasonCompletedEventHandler UploadCDNLogsPortionJasonCompleted;
        
        /// <remarks/>
        public event UploadDataOnSalesPortionJasonCompletedEventHandler UploadDataOnSalesPortionJasonCompleted;
        
        /// <remarks/>
        public event GetParametersOnBonusProgramCompletedEventHandler GetParametersOnBonusProgramCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceIsWorker", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ServiceIsWorker() {
            object[] results = this.Invoke("ServiceIsWorker", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ServiceIsWorkerAsync() {
            this.ServiceIsWorkerAsync(null);
        }
        
        /// <remarks/>
        public void ServiceIsWorkerAsync(object userState) {
            if ((this.ServiceIsWorkerOperationCompleted == null)) {
                this.ServiceIsWorkerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceIsWorkerOperationCompleted);
            }
            this.InvokeAsync("ServiceIsWorker", new object[0], this.ServiceIsWorkerOperationCompleted, userState);
        }
        
        private void OnServiceIsWorkerOperationCompleted(object arg) {
            if ((this.ServiceIsWorkerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceIsWorkerCompleted(this, new ServiceIsWorkerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTypesCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetTypesCard() {
            object[] results = this.Invoke("GetTypesCard", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTypesCardAsync() {
            this.GetTypesCardAsync(null);
        }
        
        /// <remarks/>
        public void GetTypesCardAsync(object userState) {
            if ((this.GetTypesCardOperationCompleted == null)) {
                this.GetTypesCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTypesCardOperationCompleted);
            }
            this.InvokeAsync("GetTypesCard", new object[0], this.GetTypesCardOperationCompleted, userState);
        }
        
        private void OnGetTypesCardOperationCompleted(object arg) {
            if ((this.GetTypesCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTypesCardCompleted(this, new GetTypesCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUsers(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetUsers", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync(string nick_shop, string data, string scheme) {
            this.GetUsersAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDateTimeServer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetDateTimeServer() {
            object[] results = this.Invoke("GetDateTimeServer", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetDateTimeServerAsync() {
            this.GetDateTimeServerAsync(null);
        }
        
        /// <remarks/>
        public void GetDateTimeServerAsync(object userState) {
            if ((this.GetDateTimeServerOperationCompleted == null)) {
                this.GetDateTimeServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDateTimeServerOperationCompleted);
            }
            this.InvokeAsync("GetDateTimeServer", new object[0], this.GetDateTimeServerOperationCompleted, userState);
        }
        
        private void OnGetDateTimeServerOperationCompleted(object arg) {
            if ((this.GetDateTimeServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDateTimeServerCompleted(this, new GetDateTimeServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetStatusSertificat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetStatusSertificat(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("SetStatusSertificat", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetStatusSertificatAsync(string nick_shop, string data, string scheme) {
            this.SetStatusSertificatAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void SetStatusSertificatAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.SetStatusSertificatOperationCompleted == null)) {
                this.SetStatusSertificatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetStatusSertificatOperationCompleted);
            }
            this.InvokeAsync("SetStatusSertificat", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.SetStatusSertificatOperationCompleted, userState);
        }
        
        private void OnSetStatusSertificatOperationCompleted(object arg) {
            if ((this.SetStatusSertificatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetStatusSertificatCompleted(this, new SetStatusSertificatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDiscountClientsV8DateTime_NEW", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDiscountClientsV8DateTime_NEW(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetDiscountClientsV8DateTime_NEW", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDiscountClientsV8DateTime_NEWAsync(string nick_shop, string data, string scheme) {
            this.GetDiscountClientsV8DateTime_NEWAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetDiscountClientsV8DateTime_NEWAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetDiscountClientsV8DateTime_NEWOperationCompleted == null)) {
                this.GetDiscountClientsV8DateTime_NEWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDiscountClientsV8DateTime_NEWOperationCompleted);
            }
            this.InvokeAsync("GetDiscountClientsV8DateTime_NEW", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetDiscountClientsV8DateTime_NEWOperationCompleted, userState);
        }
        
        private void OnGetDiscountClientsV8DateTime_NEWOperationCompleted(object arg) {
            if ((this.GetDiscountClientsV8DateTime_NEWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDiscountClientsV8DateTime_NEWCompleted(this, new GetDiscountClientsV8DateTime_NEWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExistsUpdateProrgam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExistsUpdateProrgam(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("ExistsUpdateProrgam", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsUpdateProrgamAsync(string nick_shop, string data, string scheme) {
            this.ExistsUpdateProrgamAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void ExistsUpdateProrgamAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.ExistsUpdateProrgamOperationCompleted == null)) {
                this.ExistsUpdateProrgamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsUpdateProrgamOperationCompleted);
            }
            this.InvokeAsync("ExistsUpdateProrgam", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.ExistsUpdateProrgamOperationCompleted, userState);
        }
        
        private void OnExistsUpdateProrgamOperationCompleted(object arg) {
            if ((this.ExistsUpdateProrgamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsUpdateProrgamCompleted(this, new ExistsUpdateProrgamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdateProgram", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetUpdateProgram(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetUpdateProgram", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdateProgramAsync(string nick_shop, string data, string scheme) {
            this.GetUpdateProgramAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetUpdateProgramAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetUpdateProgramOperationCompleted == null)) {
                this.GetUpdateProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdateProgramOperationCompleted);
            }
            this.InvokeAsync("GetUpdateProgram", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetUpdateProgramOperationCompleted, userState);
        }
        
        private void OnGetUpdateProgramOperationCompleted(object arg) {
            if ((this.GetUpdateProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdateProgramCompleted(this, new GetUpdateProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNpgsqlNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetNpgsqlNew(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetNpgsqlNew", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNpgsqlNewAsync(string nick_shop, string data, string scheme) {
            this.GetNpgsqlNewAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetNpgsqlNewAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetNpgsqlNewOperationCompleted == null)) {
                this.GetNpgsqlNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNpgsqlNewOperationCompleted);
            }
            this.InvokeAsync("GetNpgsqlNew", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetNpgsqlNewOperationCompleted, userState);
        }
        
        private void OnGetNpgsqlNewOperationCompleted(object arg) {
            if ((this.GetNpgsqlNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNpgsqlNewCompleted(this, new GetNpgsqlNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatusSertificat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStatusSertificat(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetStatusSertificat", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusSertificatAsync(string nick_shop, string data, string scheme) {
            this.GetStatusSertificatAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetStatusSertificatAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetStatusSertificatOperationCompleted == null)) {
                this.GetStatusSertificatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusSertificatOperationCompleted);
            }
            this.InvokeAsync("GetStatusSertificat", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetStatusSertificatOperationCompleted, userState);
        }
        
        private void OnGetStatusSertificatOperationCompleted(object arg) {
            if ((this.GetStatusSertificatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusSertificatCompleted(this, new GetStatusSertificatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadChangeStatusClients", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadChangeStatusClients(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("UploadChangeStatusClients", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadChangeStatusClientsAsync(string nick_shop, string data, string scheme) {
            this.UploadChangeStatusClientsAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void UploadChangeStatusClientsAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.UploadChangeStatusClientsOperationCompleted == null)) {
                this.UploadChangeStatusClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadChangeStatusClientsOperationCompleted);
            }
            this.InvokeAsync("UploadChangeStatusClients", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.UploadChangeStatusClientsOperationCompleted, userState);
        }
        
        private void OnUploadChangeStatusClientsOperationCompleted(object arg) {
            if ((this.UploadChangeStatusClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadChangeStatusClientsCompleted(this, new UploadChangeStatusClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadPhoneClients", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadPhoneClients(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("UploadPhoneClients", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadPhoneClientsAsync(string nick_shop, string data, string scheme) {
            this.UploadPhoneClientsAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void UploadPhoneClientsAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.UploadPhoneClientsOperationCompleted == null)) {
                this.UploadPhoneClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadPhoneClientsOperationCompleted);
            }
            this.InvokeAsync("UploadPhoneClients", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.UploadPhoneClientsOperationCompleted, userState);
        }
        
        private void OnUploadPhoneClientsOperationCompleted(object arg) {
            if ((this.UploadPhoneClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadPhoneClientsCompleted(this, new UploadPhoneClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadDeletedItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadDeletedItems(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("UploadDeletedItems", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadDeletedItemsAsync(string nick_shop, string data, string scheme) {
            this.UploadDeletedItemsAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void UploadDeletedItemsAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.UploadDeletedItemsOperationCompleted == null)) {
                this.UploadDeletedItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadDeletedItemsOperationCompleted);
            }
            this.InvokeAsync("UploadDeletedItems", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.UploadDeletedItemsOperationCompleted, userState);
        }
        
        private void OnUploadDeletedItemsOperationCompleted(object arg) {
            if ((this.UploadDeletedItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadDeletedItemsCompleted(this, new UploadDeletedItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTovarCheckCDN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTovarCheckCDN(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetTovarCheckCDN", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTovarCheckCDNAsync(string nick_shop, string data, string scheme) {
            this.GetTovarCheckCDNAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetTovarCheckCDNAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetTovarCheckCDNOperationCompleted == null)) {
                this.GetTovarCheckCDNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTovarCheckCDNOperationCompleted);
            }
            this.InvokeAsync("GetTovarCheckCDN", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetTovarCheckCDNOperationCompleted, userState);
        }
        
        private void OnGetTovarCheckCDNOperationCompleted(object arg) {
            if ((this.GetTovarCheckCDNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTovarCheckCDNCompleted(this, new GetTovarCheckCDNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataForCasheV8Jason", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetDataForCasheV8Jason(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetDataForCasheV8Jason", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataForCasheV8JasonAsync(string nick_shop, string data, string scheme) {
            this.GetDataForCasheV8JasonAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetDataForCasheV8JasonAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetDataForCasheV8JasonOperationCompleted == null)) {
                this.GetDataForCasheV8JasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataForCasheV8JasonOperationCompleted);
            }
            this.InvokeAsync("GetDataForCasheV8Jason", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetDataForCasheV8JasonOperationCompleted, userState);
        }
        
        private void OnGetDataForCasheV8JasonOperationCompleted(object arg) {
            if ((this.GetDataForCasheV8JasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataForCasheV8JasonCompleted(this, new GetDataForCasheV8JasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataForCasheV8Successfully", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataForCasheV8Successfully(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetDataForCasheV8Successfully", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataForCasheV8SuccessfullyAsync(string nick_shop, string data, string scheme) {
            this.GetDataForCasheV8SuccessfullyAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetDataForCasheV8SuccessfullyAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetDataForCasheV8SuccessfullyOperationCompleted == null)) {
                this.GetDataForCasheV8SuccessfullyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataForCasheV8SuccessfullyOperationCompleted);
            }
            this.InvokeAsync("GetDataForCasheV8Successfully", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetDataForCasheV8SuccessfullyOperationCompleted, userState);
        }
        
        private void OnGetDataForCasheV8SuccessfullyOperationCompleted(object arg) {
            if ((this.GetDataForCasheV8SuccessfullyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataForCasheV8SuccessfullyCompleted(this, new GetDataForCasheV8SuccessfullyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnlineCasheV8Successfully", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OnlineCasheV8Successfully(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("OnlineCasheV8Successfully", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OnlineCasheV8SuccessfullyAsync(string nick_shop, string data, string scheme) {
            this.OnlineCasheV8SuccessfullyAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void OnlineCasheV8SuccessfullyAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.OnlineCasheV8SuccessfullyOperationCompleted == null)) {
                this.OnlineCasheV8SuccessfullyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineCasheV8SuccessfullyOperationCompleted);
            }
            this.InvokeAsync("OnlineCasheV8Successfully", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.OnlineCasheV8SuccessfullyOperationCompleted, userState);
        }
        
        private void OnOnlineCasheV8SuccessfullyOperationCompleted(object arg) {
            if ((this.OnlineCasheV8SuccessfullyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnlineCasheV8SuccessfullyCompleted(this, new OnlineCasheV8SuccessfullyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataForCasheV8JasonUpdateOnly", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetDataForCasheV8JasonUpdateOnly(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetDataForCasheV8JasonUpdateOnly", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataForCasheV8JasonUpdateOnlyAsync(string nick_shop, string data, string scheme) {
            this.GetDataForCasheV8JasonUpdateOnlyAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetDataForCasheV8JasonUpdateOnlyAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetDataForCasheV8JasonUpdateOnlyOperationCompleted == null)) {
                this.GetDataForCasheV8JasonUpdateOnlyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataForCasheV8JasonUpdateOnlyOperationCompleted);
            }
            this.InvokeAsync("GetDataForCasheV8JasonUpdateOnly", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetDataForCasheV8JasonUpdateOnlyOperationCompleted, userState);
        }
        
        private void OnGetDataForCasheV8JasonUpdateOnlyOperationCompleted(object arg) {
            if ((this.GetDataForCasheV8JasonUpdateOnlyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataForCasheV8JasonUpdateOnlyCompleted(this, new GetDataForCasheV8JasonUpdateOnlyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadCDNLogsPortionJason", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadCDNLogsPortionJason(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("UploadCDNLogsPortionJason", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadCDNLogsPortionJasonAsync(string nick_shop, string data, string scheme) {
            this.UploadCDNLogsPortionJasonAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void UploadCDNLogsPortionJasonAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.UploadCDNLogsPortionJasonOperationCompleted == null)) {
                this.UploadCDNLogsPortionJasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadCDNLogsPortionJasonOperationCompleted);
            }
            this.InvokeAsync("UploadCDNLogsPortionJason", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.UploadCDNLogsPortionJasonOperationCompleted, userState);
        }
        
        private void OnUploadCDNLogsPortionJasonOperationCompleted(object arg) {
            if ((this.UploadCDNLogsPortionJasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadCDNLogsPortionJasonCompleted(this, new UploadCDNLogsPortionJasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadDataOnSalesPortionJason", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadDataOnSalesPortionJason(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("UploadDataOnSalesPortionJason", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadDataOnSalesPortionJasonAsync(string nick_shop, string data, string scheme) {
            this.UploadDataOnSalesPortionJasonAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void UploadDataOnSalesPortionJasonAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.UploadDataOnSalesPortionJasonOperationCompleted == null)) {
                this.UploadDataOnSalesPortionJasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadDataOnSalesPortionJasonOperationCompleted);
            }
            this.InvokeAsync("UploadDataOnSalesPortionJason", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.UploadDataOnSalesPortionJasonOperationCompleted, userState);
        }
        
        private void OnUploadDataOnSalesPortionJasonOperationCompleted(object arg) {
            if ((this.UploadDataOnSalesPortionJasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadDataOnSalesPortionJasonCompleted(this, new UploadDataOnSalesPortionJasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetParametersOnBonusProgram", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetParametersOnBonusProgram(string nick_shop, string data, string scheme) {
            object[] results = this.Invoke("GetParametersOnBonusProgram", new object[] {
                        nick_shop,
                        data,
                        scheme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetParametersOnBonusProgramAsync(string nick_shop, string data, string scheme) {
            this.GetParametersOnBonusProgramAsync(nick_shop, data, scheme, null);
        }
        
        /// <remarks/>
        public void GetParametersOnBonusProgramAsync(string nick_shop, string data, string scheme, object userState) {
            if ((this.GetParametersOnBonusProgramOperationCompleted == null)) {
                this.GetParametersOnBonusProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParametersOnBonusProgramOperationCompleted);
            }
            this.InvokeAsync("GetParametersOnBonusProgram", new object[] {
                        nick_shop,
                        data,
                        scheme}, this.GetParametersOnBonusProgramOperationCompleted, userState);
        }
        
        private void OnGetParametersOnBonusProgramOperationCompleted(object arg) {
            if ((this.GetParametersOnBonusProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParametersOnBonusProgramCompleted(this, new GetParametersOnBonusProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ServiceIsWorkerCompletedEventHandler(object sender, ServiceIsWorkerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceIsWorkerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceIsWorkerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTypesCardCompletedEventHandler(object sender, GetTypesCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTypesCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTypesCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDateTimeServerCompletedEventHandler(object sender, GetDateTimeServerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDateTimeServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDateTimeServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SetStatusSertificatCompletedEventHandler(object sender, SetStatusSertificatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetStatusSertificatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetStatusSertificatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDiscountClientsV8DateTime_NEWCompletedEventHandler(object sender, GetDiscountClientsV8DateTime_NEWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDiscountClientsV8DateTime_NEWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDiscountClientsV8DateTime_NEWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ExistsUpdateProrgamCompletedEventHandler(object sender, ExistsUpdateProrgamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsUpdateProrgamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsUpdateProrgamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetUpdateProgramCompletedEventHandler(object sender, GetUpdateProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdateProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdateProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetNpgsqlNewCompletedEventHandler(object sender, GetNpgsqlNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNpgsqlNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNpgsqlNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetStatusSertificatCompletedEventHandler(object sender, GetStatusSertificatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusSertificatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusSertificatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UploadChangeStatusClientsCompletedEventHandler(object sender, UploadChangeStatusClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadChangeStatusClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadChangeStatusClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UploadPhoneClientsCompletedEventHandler(object sender, UploadPhoneClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadPhoneClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadPhoneClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UploadDeletedItemsCompletedEventHandler(object sender, UploadDeletedItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadDeletedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadDeletedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTovarCheckCDNCompletedEventHandler(object sender, GetTovarCheckCDNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTovarCheckCDNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTovarCheckCDNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDataForCasheV8JasonCompletedEventHandler(object sender, GetDataForCasheV8JasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataForCasheV8JasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataForCasheV8JasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDataForCasheV8SuccessfullyCompletedEventHandler(object sender, GetDataForCasheV8SuccessfullyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataForCasheV8SuccessfullyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataForCasheV8SuccessfullyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void OnlineCasheV8SuccessfullyCompletedEventHandler(object sender, OnlineCasheV8SuccessfullyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnlineCasheV8SuccessfullyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnlineCasheV8SuccessfullyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDataForCasheV8JasonUpdateOnlyCompletedEventHandler(object sender, GetDataForCasheV8JasonUpdateOnlyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataForCasheV8JasonUpdateOnlyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataForCasheV8JasonUpdateOnlyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UploadCDNLogsPortionJasonCompletedEventHandler(object sender, UploadCDNLogsPortionJasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadCDNLogsPortionJasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadCDNLogsPortionJasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UploadDataOnSalesPortionJasonCompletedEventHandler(object sender, UploadDataOnSalesPortionJasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadDataOnSalesPortionJasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadDataOnSalesPortionJasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetParametersOnBonusProgramCompletedEventHandler(object sender, GetParametersOnBonusProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParametersOnBonusProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParametersOnBonusProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591